site_name: "Lakshit's corner"
author: "you"
base_url: "you.com"

theme:
  default: "coffee"
  include:
    - "hacktoberfest25"
    - "dracula"
    - "coffee"
  custom:
    hacktoberfest25: |
      /* Raw CSS Theme */
      prefers-dark: true;
      color-scheme: dark;
      --color-base-100: #1C1C3F;
      --color-base-200: #403F7D;
      --color-base-300: #5E577C;
      --color-base-content: oklch(1.000 0.000 0.0);
      --color-primary: #A0A0FF;
      --color-primary-content: #1C1C3F;
      --color-secondary: #5A5AB5;
      --color-secondary-content: #FFFFFF;
      --color-accent: #C2C2FF;
      --color-accent-content: #1C1C3F;
      --color-neutral: #403F7D;
      --color-neutral-content: #FFFFFF;
      --color-info: oklch(88% 0.059 254.128);
      --color-info-content: oklch(29% 0.066 243.157);
      --color-success: oklch(77% 0.152 181.912);
      --color-success-content: oklch(27% 0.046 192.524);
      --color-warning: #fbbd23;
      --color-warning-content: oklch(28% 0.066 53.813);
      --color-error: #f87272;
      --color-error-content: oklch(25% 0.092 26.042);
      --radius-selector: 2rem;
      --radius-field: 1rem;
      --radius-box: 1rem;
      --size-selector: 0.28125rem;
      --size-field: 0.25rem;
      --border: 1px;
      --depth: 0;
      --noise: 1;
fonts:
  imports:
    - "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap"
  families:
    body: "'Inter', sans-serif"
    heading: "'Space Grotesk', sans-serif"
    mono: "'JetBrains Mono', monospace"

syntax:
  pygments_theme: "dracula"

markdown:
  extensions:
    - fenced_code
    - codehilite
    - footnotes
    - tables
    - attr_list
    - sane_lists
    - md_in_html
    - nl2br
    - toc:
        permalink: true

images:
  formats:
    - webp
    - jpg


navigation:
  - name: "Home"
    url: "/"
  - name: "Blog"
    url: "/blog/"
  - name: "Pictures"
    url: "/pics/"
  - name: "Projects"
    url: "/projects/"

lastfm_api_key: "5f7ae3b17413db14e81ed1423684db51"
lastfm_user: "talrejalakshit"
